#SPDX-License-Identifier: MIT-0
---
# tasks file for redis_server


- name: Install redis on Rocky Linux
  ansible.builtin.dnf:
    name: redis
    state: present
  when: "ansible_facts['distribution'] == 'Rocky'"
